name: CI

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    name: 'PHPUnit'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Install Dependencies
        run: composer install
      - name: PHPUnit
        run: vendor/bin/phpunit --colors=auto
